services:
  n8n:
    image: n8nio/n8n:latest
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - xproflow

  nginx:
    image: nginx:latest
    depends_on:
      - xproflow-api
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - xproflow

  xproflow-api:
    build: ./api
    env_file:
      - .env.runtime
    expose:
      - "3001"
    networks:
      - xproflow

networks:
  xproflow:
    driver: bridge

volumes:
  n8n_data:
