services:
  n8n:
    image: n8nio/n8n:latest
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - xproflow
    environment:
      - N8N_HOST=n8n.xproflow.com
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.xproflow.com/
      - N8N_EDITOR_BASE_URL=https://n8n.xproflow.com/

  nginx:
    image: nginx:latest
    depends_on:
      - xproflow-api
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - xproflow

  xproflow-api:
    build: ./api
    env_file:
      - .env.runtime
    environment:
      AWS_SECRET_NAME: xproflow-secret
      AWS_REGION: eu-north-1
    expose:
      - "3001"
    networks:
      - xproflow

networks:
  xproflow:
    driver: bridge

volumes:
  n8n_data:
    external: true
    name: n8n_data
